#!/usr/bin/env python3
"""
Generate d3dx9_43.def — a complete export-forwarder .def for the cheat-engine
proxy d3dx9_43.dll.

WHY: the cheat engine is carried in d3dx9_43.dll (a DX9 helper lib that Wine
loads ": native" from disk on arm64ec Proton, unlike dinput8 which is forced to
": builtin"). d3dx9_43 has ~329 exports; hand-writing forwarding stubs for all
of them is impractical and any missed export would crash the game. Instead we
emit a .def where EVERY export forwards to the genuine library renamed to
d3dx9_43_real.dll (CheatStager stages the prefix's real system32 d3dx9_43.dll
next to the exe under that name). The Windows/Wine loader resolves the
forwarders itself, so all exports reach the real lib with zero hand-written
stubs and zero missing-export risk — while our own DllMain still runs the
cheat engine.

INPUT : a gendef dump of the genuine d3dx9_43.dll (committed as
        d3dx9_43_real_src.def so the build is reproducible without the host's
        system32). Regenerate that dump with:
            gendef /c/Windows/System32/d3dx9_43.dll
        and rename the output to d3dx9_43_real_src.def.
OUTPUT: d3dx9_43.def (the forwarder def the linker consumes).

Run from the cheatdll directory:  python build_def.py
"""
import re
import sys
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DEF = os.path.join(HERE, "d3dx9_43_real_src.def")
OUT_DEF = os.path.join(HERE, "d3dx9_43.def")
SIDECAR = "d3dx9_43_real"  # the renamed genuine lib staged next to the exe

# Exports that proxy.c implements as REAL C trampolines (NOT .def forwarders): on
# their first call they start the cheat engine once (idempotent), then forward to
# d3dx9_43_real.<Name> themselves via LoadLibrary+GetProcAddress. A name is EITHER a
# real export OR a .def forwarder, never both, so these are excluded from the
# forwarder list below to avoid a duplicate-symbol link error. Chosen because
# Bayonetta imports them AND they are common across DX9 games (per-frame math
# helpers + startup helpers) — covering both call phases starts the engine ASAP
# regardless of call order. KEEP IN SYNC with the __declspec(dllexport) trampolines
# in proxy.c.
TRAMPOLINE_NAMES = {
    # per-frame hot-path math helpers (trivial, stable signatures)
    "D3DXMatrixMultiply",
    "D3DXMatrixTranslation",
    "D3DXMatrixInverse",
    "D3DXMatrixTranspose",
    "D3DXMatrixRotationY",
    "D3DXVec3TransformCoord",
    "D3DXVec3Normalize",
    # startup-time helpers (cover late math-helper call order)
    "D3DXCreateTexture",
    "D3DXCompileShader",
    "D3DXGetShaderConstantTable",
}


def parse_exports(path):
    names = []
    started = False
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            s = line.strip()
            if s == "EXPORTS":
                started = True
                continue
            if not started or not s or s.startswith(";") or s.startswith("LIBRARY"):
                continue
            m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)", s)
            if m:
                names.append(m.group(1))
    # de-dupe, preserve order
    seen = set()
    uniq = []
    for n in names:
        if n not in seen:
            seen.add(n)
            uniq.append(n)
    return uniq


def main():
    if not os.path.isfile(SRC_DEF):
        sys.stderr.write("ERROR: %s not found. Regenerate with gendef (see header).\n" % SRC_DEF)
        return 1
    names = parse_exports(SRC_DEF)
    if not names:
        sys.stderr.write("ERROR: no exports parsed from %s\n" % SRC_DEF)
        return 1

    # Sanity: every trampoline name must exist in the genuine export table, else a
    # typo would silently leave a forwarder in (duplicate symbol) or drop coverage.
    missing = sorted(TRAMPOLINE_NAMES - set(names))
    if missing:
        sys.stderr.write("ERROR: TRAMPOLINE_NAMES not found in %s: %s\n" % (SRC_DEF, ", ".join(missing)))
        return 1

    # The trampolined names are REAL exports in proxy.c; drop them from the forwarders.
    forwarders = [n for n in names if n not in TRAMPOLINE_NAMES]

    with open(OUT_DEF, "w", encoding="utf-8", newline="\r\n") as out:
        out.write("; d3dx9_43.dll proxy export forwarders.\n")
        out.write("; AUTO-GENERATED by build_def.py from the genuine d3dx9_43.dll export table.\n")
        out.write("; The %d forwarders below reach the renamed genuine library staged next to the\n" % len(forwarders))
        out.write("; game exe as d3dx9_43_real.dll (CheatStager stages it). The loader resolves\n")
        out.write("; these forwarders itself, so the game's d3dx9 calls reach the real lib with\n")
        out.write("; ZERO hand-written stubs -> no missing-export crash.\n")
        out.write(";\n")
        out.write("; The %d TRIGGER exports below are NOT here on purpose — they are REAL C\n" % len(TRAMPOLINE_NAMES))
        out.write("; trampolines in proxy.c that start the cheat engine on first call (idempotent)\n")
        out.write("; then forward to d3dx9_43_real.<Name> themselves:\n")
        for n in sorted(TRAMPOLINE_NAMES):
            out.write(";     %s\n" % n)
        out.write("; A name is EITHER a real export OR a forwarder, never both — listing them here\n")
        out.write("; too would be a duplicate-symbol link error. Regenerate by editing/refreshing\n")
        out.write("; d3dx9_43_real_src.def then running: python build_def.py\n")
        out.write(";\n")
        out.write("; WHY START FROM AN EXPORT (device-diagnosed): on this arm64ec Wine/FEX stack\n")
        out.write("; the loader MAPS a native x86_64 DLL and thunks its exports on demand but does\n")
        out.write("; NOT call its DllMain — so the engine must bootstrap from a function the game\n")
        out.write("; actually CALLS, not from DllMain. See proxy.c's BREAKTHROUGH REDESIGN note.\n")
        out.write(";\n")
        out.write("; NO `LIBRARY d3dx9_43.dll` line here on purpose (internal name comes from the\n")
        out.write("; output filename). GnCheatEngineMarker is a harmless real marker export.\n")
        out.write(";\n")
        out.write("; The proxy is linked CRT-FREE so libc binds to Wine-builtin msvcrt.dll:\n")
        out.write(";   x86_64-w64-mingw32-gcc -shared -O2 -s -nostartfiles -e DllMain \\\n")
        out.write(";       -nodefaultlibs -o d3dx9_43.dll proxy.c cheat.c d3dx9_43.def \\\n")
        out.write(";       -lmsvcrt-os -lkernel32\n")
        out.write("; (-lmsvcrt-os, NOT -lmsvcrt; see README.md + crt_msvcrt_shim.h.)\n")
        out.write("EXPORTS\n")
        for n in forwarders:
            out.write("%s=%s.%s\n" % (n, SIDECAR, n))
        # One real (non-forwarder) export marker. Defined in proxy.c as
        # `__declspec(dllexport) int GnCheatEngineMarker(void)`. Harmless and never
        # called by the game (not a d3dx9 name).
        out.write("GnCheatEngineMarker\n")
    sys.stdout.write("Wrote %s with %d forwarders (+ %d real trampolines in proxy.c + 1 marker)\n"
                     % (OUT_DEF, len(forwarders), len(TRAMPOLINE_NAMES)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
