/*
 * proxy.c — a proxy d3dx9_43.dll that force-loads our in-process cheat engine
 * INTO the game process under Box64/Wine (incl. arm64ec Proton) on Android.
 *
 * WHY d3dx9_43.dll (NOT dinput8.dll) IS THE CARRIER — device-proven:
 *   On arm64ec Proton, Wine FORCES dinput8/winmm/xinput/version + all core DLLs
 *   to ": builtin" — they are Wine arm64ec hybrid builtins and the loader ignores
 *   any disk PE in those slots. We proved on-device that an x86_64 proxy physically
 *   at system32\dinput8.dll WITH *dinput8=n,b STILL loaded ": builtin": our DllMain
 *   never ran, cheat_proof.txt never appeared, the engine never started.
 *
 *   BUT Wine loads these ": native" from disk on the SAME launch: d3d9, d3dx9_43,
 *   d3dcompiler_43, MSVCR100, MSVCP100. d3dx9_43 is a DX9 HELPER lib that sits OFF
 *   the DXVK render path (DXVK owns d3d9/dxgi — untouched here), so replacing it does
 *   NOT break rendering. The repo already ships "d3dx9_43=native,builtin" for game
 *   413420 (gamefixes/registry.json) — proving a d3dx9_43 native override works on
 *   this exact stack. Bayonetta imports d3dx9_43 and it loaded ": native" at 7B7B0000
 *   in the loaddll trace. So d3dx9_43, planted in the EXE DIR and overridden n,b, is
 *   the slot that actually runs our DllMain.
 *
 * FORWARDING — why the game does NOT crash on a missing export:
 *   d3dx9_43 has ~329 exports. Hand-writing runtime GetProcAddress stubs for all of
 *   them (the old dinput8 approach) is impractical and any missed export crashes the
 *   game. Instead this DLL is linked with d3dx9_43.def (auto-generated by build_def.py
 *   from the genuine lib's export table), where EVERY export is a static forwarder:
 *       D3DXCreateTextureFromFileW = d3dx9_43_real.D3DXCreateTextureFromFileW
 *   CheatStager stages the prefix's genuine system32\d3dx9_43.dll next to the exe as
 *   d3dx9_43_real.dll. The Wine/Windows loader resolves every forwarder itself, so
 *   ALL 329 d3dx9 functions the game calls reach the real implementation — complete
 *   coverage, zero hand-written stubs, no missing-export crash. This file therefore
 *   exports NOTHING by hand; the .def is the entire export surface.
 *
 * COEXISTENCE WITH A FLiNG TRAINER (chain-load): a FLiNG trainer is a dinput8.dll.
 * It is staged next to the exe under its normal name (or dinput8.fling.dll — see
 * FlingStager); after starting our engine we chain-load the sibling so its hotkey
 * overlay also initialises in the same process. Absent → harmless no-op.
 *
 * It bootstraps the cheat engine ONCE, doing THREE things:
 *   1. write_proof()       — a proof file with PID + host-exe base, visible proof we
 *                            ran INSIDE the game's address space.
 *   2. cheat_engine_start()— start the in-process freeze/poll cheat thread (cheat.c).
 *   3. chain_load_fling()  — pull in a sibling FLiNG trainer dll if present.
 *
 * ===========================================================================
 * BREAKTHROUGH REDESIGN (device-diagnosed): START FROM AN EXPORT, NOT DllMain
 * ===========================================================================
 *   On-device we PROVED our proxy maps ": native" (at 0x7B7B0000) but its DllMain
 *   NEVER runs — we exhausted every fix (system32 placement, non-pure-forwarder
 *   table, CRT-free build importing only kernel32+msvcrt). ROOT CAUSE: on this
 *   arm64ec Wine/FEX stack the loader MAPS a native x86_64 DLL and THUNKS its
 *   exported functions when the game CALLS them, but it does NOT invoke the
 *   x86_64 DLL's DllMain/entry init. (DXVK's d3d9 works precisely because the game
 *   CALLS its exports — not via DllMain.)
 *
 *   THE FIX: bootstrap the engine from INSIDE a set of EXPORTED FUNCTIONS the game
 *   actually calls. We convert a handful of guaranteed-called d3dx9 exports from
 *   pure .def forwarders into REAL C trampolines. On the FIRST call, the trampoline
 *   starts the engine ONCE (idempotent atomic guard), then forwards to the REAL
 *   implementation in d3dx9_43_real.dll (LoadLibraryW + GetProcAddress, cast to the
 *   correct d3dx9 prototype). The remaining ~320 exports stay pure .def forwarders.
 *
 *   The DllMain body is KEPT as belt-and-braces (it also calls ensure_engine_started)
 *   — harmless if DllMain never runs, and a free win on any stack where it does.
 *
 * WHICH EXPORTS WE TRAMPOLINE (Bayonetta-imported AND common across DX9 games):
 *   Per-frame hot-path math helpers (called constantly from the very first frame,
 *   so the engine starts ASAP) — trivial, stable, well-defined signatures:
 *     D3DXMatrixMultiply, D3DXMatrixTranslation, D3DXMatrixInverse,
 *     D3DXMatrixTranspose, D3DXMatrixRotationY, D3DXVec3TransformCoord,
 *     D3DXVec3Normalize
 *   Startup-time helpers (cover the case where math helpers are called late):
 *     D3DXCreateTexture, D3DXCompileShader, D3DXGetShaderConstantTable
 *   Covering BOTH per-frame and startup means the engine starts regardless of call
 *   order. These names are REMOVED from the .def forwarder list (a name is EITHER a
 *   real export OR a forwarder, never both) — see build_def.py TRAMPOLINE_NAMES.
 *
 * Build (x86_64 PE) — the .def supplies the exports. CRT-FREE so DllMain runs:
 *   x86_64-w64-mingw32-gcc -shared -O2 -s -nostartfiles -e DllMain -nodefaultlibs \
 *       -o d3dx9_43.dll proxy.c cheat.c d3dx9_43.def -lmsvcrt-os -lkernel32
 *   (`-nostartfiles -e DllMain` makes DllMain the PE entry point, so there is NO
 *    DllMainCRTStartup/_CRT_INIT to fail; `-nodefaultlibs ... -lmsvcrt-os` binds libc
 *    to Wine's builtin msvcrt.dll instead of the UCRT api-ms-win-crt-* apisets. See
 *    the ENTRY-POINT note at the bottom of this file and crt_msvcrt_shim.h.)
 *
 * CARRIER FALLBACK CHAIN (per-game, via TrainerEntry.proxyName / registry):
 *   d3dx9_43 (DX9, default)  →  d3dx11_43 (DX11)  →  d3dcompiler_47  →  (last
 *   resort) a dxgi chain-forward carrier. Only d3dx9_43 is built here; the others
 *   would each need their own generated forwarder .def from the genuine lib.
 */
#include <windows.h>
#include <stdio.h>
#include "crt_msvcrt_shim.h"  /* route libc onto Wine-builtin msvcrt.dll (no UCRT apisets / _CRT_INIT) */

/* Defined in cheat.c — starts the in-process freeze/poll thread. */
void cheat_engine_start(void);

/* Write the proof file. Tries a few temp locations so at least one is writable
 * inside the Wine prefix. The Android side reads it back via run-as. */
static void write_proof(void)
{
    const wchar_t *candidates[] = {
        L"C:\\users\\steamuser\\Temp\\cheat_proof.txt",
        L"C:\\windows\\temp\\cheat_proof.txt",
        L"C:\\cheat_proof.txt",
    };

    char modpath[MAX_PATH]; modpath[0] = '\0';
    GetModuleFileNameA(NULL, modpath, sizeof(modpath));   /* the HOST exe */
    HMODULE self = GetModuleHandleW(NULL);

    char line[1024];
    snprintf(line, sizeof(line),
             "CHEATDLL LOADED\r\ncarrier=d3dx9_43.dll\r\npid=%lu\r\nhost_exe=%s\r\nimage_base=%p\r\n",
             (unsigned long)GetCurrentProcessId(),
             modpath,
             (void *)self);

    for (int i = 0; i < 3; i++) {
        HANDLE h = CreateFileW(candidates[i], GENERIC_WRITE, FILE_SHARE_READ,
                               NULL, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
        if (h != INVALID_HANDLE_VALUE) {
            DWORD wrote = 0;
            WriteFile(h, line, (DWORD)strlen(line), &wrote, NULL);
            CloseHandle(h);
            /* Also emit to the debugger channel (WINEDEBUG / Box64 log). */
            OutputDebugStringA("[cheatdll] proof written (d3dx9_43 carrier)");
            return;
        }
    }
    OutputDebugStringA("[cheatdll] FAILED to write any proof file");
}

/*
 * Chain-load a sibling FLiNG trainer staged next to the GAME EXE.
 *
 * A FLiNG trainer is itself a dinput8.dll; since our carrier is d3dx9_43 the FLiNG
 * dll keeps its own slot (FlingStager stages it next to the exe, as dinput8.fling.dll
 * when a name clash must be avoided). We resolve the sibling against the GAME EXE's
 * directory (GetModuleFileNameA(NULL) → strip filename → append the sibling name) so
 * we find it regardless of where our proxy loaded from, then fall back to a bare name
 * (Wine's default search path includes the exe dir).
 *
 * GUARD: every step is null/bounds-checked and LoadLibrary reports failure by
 * returning NULL (it does not throw), so a missing or broken fling dll is a clean
 * no-op — it can never break the game or our engine. (Plain C guard rather than MSVC
 * SEH, since the mingw GCC toolchain that builds this DLL has no __try/__except.)
 */
static void chain_load_fling(HINSTANCE self)
{
    (void)self;   /* the fling dll lives next to the HOST EXE, not next to us */

    char exepath[MAX_PATH];
    DWORD n = GetModuleFileNameA(NULL, exepath, sizeof(exepath));   /* the HOST exe */
    if (n > 0 && n < sizeof(exepath)) {
        /* Strip the exe filename, append the sibling trainer name. */
        for (DWORD i = n; i > 0; i--) {
            if (exepath[i - 1] == '\\' || exepath[i - 1] == '/') {
                exepath[i] = '\0';
                break;
            }
        }
        /* Only append if there is room for the sibling name + NUL. */
        if ((int)strlen(exepath) + (int)sizeof("dinput8.fling.dll") < (int)sizeof(exepath)) {
            lstrcatA(exepath, "dinput8.fling.dll");
            if (LoadLibraryA(exepath)) {
                OutputDebugStringA("[cheatdll] chain-loaded dinput8.fling.dll (exe-dir abs)");
                return;
            }
        }
    }
    /* Fallback: bare name — the default DLL search path includes the exe dir. */
    if (LoadLibraryW(L"dinput8.fling.dll")) {
        OutputDebugStringA("[cheatdll] chain-loaded dinput8.fling.dll (name)");
    }
}

/* ---------------------------------------------------------------------------
 * ONE-TIME ENGINE BOOTSTRAP — triggered from an EXPORT (see redesign note above),
 * and also from DllMain as belt-and-braces.
 *
 * IDEMPOTENCY: the trigger exports below are called thousands of times per frame.
 * ensure_engine_started() must start the engine EXACTLY ONCE with near-zero
 * per-call overhead afterwards. We use an InterlockedCompareExchange (kernel32)
 * atomic guard: the very first caller flips g_engine_started 0->1 and runs the
 * bootstrap; every subsequent caller sees it already 1 and returns immediately
 * (a single interlocked compare — no lock, no allocation, no syscall).
 * --------------------------------------------------------------------------- */
static volatile LONG g_engine_started = 0;

/* HMODULE of THIS proxy DLL. Captured in DllMain when it runs; otherwise NULL
 * (the engine bootstrap does not need it — write_proof/chain_load_fling resolve
 * everything against the HOST exe, not against us). */
static HINSTANCE g_self_module = NULL;

static void ensure_engine_started(void)
{
    /* Fast path: already started -> single interlocked read, return. */
    if (InterlockedCompareExchange(&g_engine_started, 1, 0) == 0) {
        /* We are the FIRST caller. Run the bootstrap exactly once. */
        write_proof();
        cheat_engine_start();          /* start the in-process freeze/poll engine */
        chain_load_fling(g_self_module); /* pull in a FLiNG trainer if present */
    }
}

/* ---------------------------------------------------------------------------
 * REAL-LIBRARY FORWARDING for the trampolined exports.
 *
 * We do NOT rely on the .def forwarder for these names (they are real exports now,
 * removed from the .def). Instead each trampoline forwards by hand: load
 * d3dx9_43_real.dll ONCE (the same renamed genuine lib CheatStager already stages
 * next to the exe AND in system32 — so LoadLibraryW finds it on the standard search
 * path), GetProcAddress the real function, cast to the correct d3dx9 prototype, and
 * tail-call it so the game gets the genuine result. Getting the signature right is
 * load-bearing: a wrong prototype corrupts the game's per-frame math. The math
 * helper signatures are stable and well-defined (from d3dx9math.h / d3dx9tex.h /
 * d3dx9shader.h); we declare the minimal types here rather than #include <d3dx9.h>
 * to keep the import table at kernel32+msvcrt only (the full DX9/COM header chain
 * would drag in CRT/FP apiset deps and break the CRT-free build).
 *
 * The real-lib handle is cached behind the same idempotent pattern. get_real_proc()
 * is safe under concurrent first-frame calls: LoadLibraryW refcounts and returns the
 * same HMODULE, and a benign double GetProcAddress just returns the same pointer. We
 * publish the cached HMODULE with an interlocked store so other threads observe a
 * fully-resolved handle.
 * --------------------------------------------------------------------------- */
static HMODULE g_real_lib = NULL;   /* d3dx9_43_real.dll, lazily loaded */

static FARPROC get_real_proc(const char *name)
{
    HMODULE lib = (HMODULE)InterlockedCompareExchangePointer((PVOID volatile *)&g_real_lib,
                                                             NULL, NULL);
    if (!lib) {
        lib = LoadLibraryW(L"d3dx9_43_real.dll");
        if (!lib) {
            /* Fallback: absolute path next to the HOST exe (belt-and-braces; the
             * bare name normally resolves via the exe dir + system32 search path). */
            char p[MAX_PATH];
            DWORD n = GetModuleFileNameA(NULL, p, sizeof(p));
            if (n > 0 && n < sizeof(p)) {
                for (DWORD i = n; i > 0; i--) {
                    if (p[i - 1] == '\\' || p[i - 1] == '/') { p[i] = '\0'; break; }
                }
                if ((int)strlen(p) + (int)sizeof("d3dx9_43_real.dll") < (int)sizeof(p)) {
                    lstrcatA(p, "d3dx9_43_real.dll");
                    lib = LoadLibraryA(p);
                }
            }
        }
        if (lib) {
            /* Publish the handle; refcount stays >=1 for process lifetime. */
            InterlockedExchangePointer((PVOID volatile *)&g_real_lib, (PVOID)lib);
        }
    }
    if (!lib)
        return NULL;
    return GetProcAddress(lib, name);
}

/* --- Minimal d3dx9 math types (layout-exact, from d3dx9math.h). ----------- */
typedef struct D3DXVECTOR3 { float x, y, z; } D3DXVECTOR3;
typedef struct D3DXVECTOR4 { float x, y, z, w; } D3DXVECTOR4;
typedef struct D3DXMATRIX  { float m[4][4]; } D3DXMATRIX;   /* 16 floats, row-major */

/* d3dx9 / d3d9 opaque-ish types used only as pointers in our trampolines. */
typedef void  IDirect3DDevice9;
typedef void  IDirect3DTexture9;
typedef void  ID3DXConstantTable;
typedef void  ID3DXInclude;
typedef void  ID3DXBuffer;
typedef long  HRESULT;
typedef unsigned int   D3DFORMAT;
typedef unsigned long  D3DCOLOR;     /* (unused arg type placeholder) */
typedef unsigned int   DWORD32_;     /* (unused) */
typedef const char *   LPCSTR_;      /* alias to avoid windows.h macro churn */

/* Function-pointer prototypes for the REAL exports (exact d3dx9 signatures). */
typedef D3DXMATRIX*  (WINAPI *pfn_MatMul)(D3DXMATRIX*, const D3DXMATRIX*, const D3DXMATRIX*);
typedef D3DXMATRIX*  (WINAPI *pfn_MatTranslation)(D3DXMATRIX*, float, float, float);
typedef D3DXMATRIX*  (WINAPI *pfn_MatInverse)(D3DXMATRIX*, float*, const D3DXMATRIX*);
typedef D3DXMATRIX*  (WINAPI *pfn_MatTranspose)(D3DXMATRIX*, const D3DXMATRIX*);
typedef D3DXMATRIX*  (WINAPI *pfn_MatRotationY)(D3DXMATRIX*, float);
typedef D3DXVECTOR3* (WINAPI *pfn_Vec3TransformCoord)(D3DXVECTOR3*, const D3DXVECTOR3*, const D3DXMATRIX*);
typedef D3DXVECTOR3* (WINAPI *pfn_Vec3Normalize)(D3DXVECTOR3*, const D3DXVECTOR3*);
typedef HRESULT      (WINAPI *pfn_CreateTexture)(IDirect3DDevice9*, UINT, UINT, UINT, DWORD, D3DFORMAT, DWORD, IDirect3DTexture9**);
typedef HRESULT      (WINAPI *pfn_CompileShader)(const char*, UINT, const void*, ID3DXInclude*, const char*, const char*, DWORD, ID3DXBuffer**, ID3DXBuffer**, ID3DXConstantTable**);
typedef ID3DXConstantTable* (WINAPI *pfn_GetShaderConstantTable)(const DWORD*, ID3DXConstantTable**);

/* ---------------------------------------------------------------------------
 * THE TRIGGER TRAMPOLINES — REAL exported functions (not .def forwarders).
 * Each: (1) ensure_engine_started() FIRST (idempotent, exactly-once),
 *       (2) resolve the real fn from d3dx9_43_real.dll and tail-call it,
 *           returning its genuine result so the game's math is unchanged.
 * If the real fn cannot be resolved (should never happen — sidecar is staged),
 * we return a safe neutral value rather than crashing.
 * --------------------------------------------------------------------------- */

__declspec(dllexport) D3DXMATRIX* WINAPI
D3DXMatrixMultiply(D3DXMATRIX *pOut, const D3DXMATRIX *pM1, const D3DXMATRIX *pM2)
{
    ensure_engine_started();
    pfn_MatMul real = (pfn_MatMul)get_real_proc("D3DXMatrixMultiply");
    if (real) return real(pOut, pM1, pM2);
    return pOut;
}

__declspec(dllexport) D3DXMATRIX* WINAPI
D3DXMatrixTranslation(D3DXMATRIX *pOut, float x, float y, float z)
{
    ensure_engine_started();
    pfn_MatTranslation real = (pfn_MatTranslation)get_real_proc("D3DXMatrixTranslation");
    if (real) return real(pOut, x, y, z);
    return pOut;
}

__declspec(dllexport) D3DXMATRIX* WINAPI
D3DXMatrixInverse(D3DXMATRIX *pOut, float *pDeterminant, const D3DXMATRIX *pM)
{
    ensure_engine_started();
    pfn_MatInverse real = (pfn_MatInverse)get_real_proc("D3DXMatrixInverse");
    if (real) return real(pOut, pDeterminant, pM);
    return pOut;   /* NULL would be the genuine "non-invertible" return; pOut is safe-ish */
}

__declspec(dllexport) D3DXMATRIX* WINAPI
D3DXMatrixTranspose(D3DXMATRIX *pOut, const D3DXMATRIX *pM)
{
    ensure_engine_started();
    pfn_MatTranspose real = (pfn_MatTranspose)get_real_proc("D3DXMatrixTranspose");
    if (real) return real(pOut, pM);
    return pOut;
}

__declspec(dllexport) D3DXMATRIX* WINAPI
D3DXMatrixRotationY(D3DXMATRIX *pOut, float Angle)
{
    ensure_engine_started();
    pfn_MatRotationY real = (pfn_MatRotationY)get_real_proc("D3DXMatrixRotationY");
    if (real) return real(pOut, Angle);
    return pOut;
}

__declspec(dllexport) D3DXVECTOR3* WINAPI
D3DXVec3TransformCoord(D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV, const D3DXMATRIX *pM)
{
    ensure_engine_started();
    pfn_Vec3TransformCoord real = (pfn_Vec3TransformCoord)get_real_proc("D3DXVec3TransformCoord");
    if (real) return real(pOut, pV, pM);
    return pOut;
}

__declspec(dllexport) D3DXVECTOR3* WINAPI
D3DXVec3Normalize(D3DXVECTOR3 *pOut, const D3DXVECTOR3 *pV)
{
    ensure_engine_started();
    pfn_Vec3Normalize real = (pfn_Vec3Normalize)get_real_proc("D3DXVec3Normalize");
    if (real) return real(pOut, pV);
    return pOut;
}

__declspec(dllexport) HRESULT WINAPI
D3DXCreateTexture(IDirect3DDevice9 *pDevice, UINT Width, UINT Height, UINT MipLevels,
                  DWORD Usage, D3DFORMAT Format, DWORD Pool, IDirect3DTexture9 **ppTexture)
{
    ensure_engine_started();
    pfn_CreateTexture real = (pfn_CreateTexture)get_real_proc("D3DXCreateTexture");
    if (real) return real(pDevice, Width, Height, MipLevels, Usage, Format, Pool, ppTexture);
    return (HRESULT)0x80004005L;   /* E_FAIL — only ever returned if the sidecar is missing */
}

__declspec(dllexport) HRESULT WINAPI
D3DXCompileShader(const char *pSrcData, UINT SrcDataLen, const void *pDefines,
                  ID3DXInclude *pInclude, const char *pFunctionName, const char *pProfile,
                  DWORD Flags, ID3DXBuffer **ppShader, ID3DXBuffer **ppErrorMsgs,
                  ID3DXConstantTable **ppConstantTable)
{
    ensure_engine_started();
    pfn_CompileShader real = (pfn_CompileShader)get_real_proc("D3DXCompileShader");
    if (real) return real(pSrcData, SrcDataLen, pDefines, pInclude, pFunctionName, pProfile,
                          Flags, ppShader, ppErrorMsgs, ppConstantTable);
    return (HRESULT)0x80004005L;   /* E_FAIL */
}

__declspec(dllexport) ID3DXConstantTable* WINAPI
D3DXGetShaderConstantTable(const DWORD *pFunction, ID3DXConstantTable **ppConstantTable)
{
    ensure_engine_started();
    pfn_GetShaderConstantTable real = (pfn_GetShaderConstantTable)get_real_proc("D3DXGetShaderConstantTable");
    if (real) return real(pFunction, ppConstantTable);
    return NULL;
}

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID reserved)
{
    (void)reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(inst);
        g_self_module = inst;     /* captured for chain_load_fling if DllMain runs */
        /* Belt-and-braces: if DllMain DOES run on some stack, start the engine here
         * too. Idempotent — if an export already started it, this is a no-op. */
        ensure_engine_started();
    }
    return TRUE;
}

/* d3dx9_43.def supplies the ~320 REMAINING export FORWARDERS to d3dx9_43_real.dll,
 * resolved by the loader. The 10 trigger exports above (D3DXMatrixMultiply, …,
 * D3DXGetShaderConstantTable) are REAL exports defined in this file and are REMOVED
 * from the .def (build_def.py TRAMPOLINE_NAMES) — a name is either a real export or a
 * forwarder, never both. See the file header for why a .def forwarder table is the
 * crash-safe choice for the rest of this 329-export helper lib.
 *
 * ENTRY-POINT / DllMain-RUNS FIX (device-diagnosed, ROOT CAUSE = UCRT _CRT_INIT):
 * the carrier mapped ": native" on-device but DllMain never ran (no proof file, no
 * engine). The PE entry point was correct, but it pointed at DllMainCRTStartup ->
 * _CRT_INIT -> DllMain, and the proxy (built with the WinLibs *UCRT* mingw flavour)
 * imported api-ms-win-crt-* apisets + carried a .tls CRT directory. On arm64ec Wine
 * that UCRT _CRT_INIT could not complete in the emulated x86_64 context, returned
 * early, and OUR DllMain was never called.
 *   THE FIX (two parts):
 *     1) Build `-nostartfiles -e DllMain`: DllMain IS the PE entry point now, so there
 *        is no DllMainCRTStartup/_CRT_INIT to fail — DllMain runs directly on load.
 *     2) Build `-nodefaultlibs ... -lmsvcrt-os -lkernel32` (NOT -lmsvcrt, which on this
 *        UCRT toolchain is just an alias bundle that forwards to the apisets): this
 *        binds atof/strtol/strtoull/memset/strchr/_vsnprintf/etc. to Wine's BUILTIN
 *        msvcrt.dll, which needs no apiset/CRT init. The C99 `snprintf` the sources use
 *        is mapped onto msvcrt's `_vsnprintf` by crt_msvcrt_shim.h (msvcrt only exports
 *        `_snprintf`/`_vsnprintf`). Result: the DLL imports ONLY kernel32 + msvcrt.dll,
 *        no api-ms-win-crt-*, no ucrtbase, no .tls. Verify with objdump -p.
 *   NOTE: the UCRT _CRT_INIT theory above was NOT the whole story. On-device the
 * CRT-free build STILL did not run DllMain — the real root cause is that this
 * arm64ec Wine/FEX loader maps a native x86_64 DLL and thunks its exports on demand
 * but never calls its DllMain (see the BREAKTHROUGH REDESIGN note at the top of this
 * file). The CRT-free flags remain correct and necessary; the engine is now started
 * from the trigger exports instead of (only) DllMain.
 *   The GnCheatEngineMarker real export below is kept as a harmless export-table
 * marker (never called by the game; not a d3dx9 name). */
__declspec(dllexport) int GnCheatEngineMarker(void) { return 1; }
